---
name: ci
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          clean: true

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: " "
          
      - name: echo changed files
        run: |
          echo ${{ steps.file_changes.outputs.files }}

      - name: loop changed files
        run: |
          IFS=' ' read -ra changed_files <<< "${{ steps.file_changes.outputs.files }}"
          for i in "${changed_files[@]}"; do
            if (echo $i | perl -nle'exit 0 if m{(?<!test\/)blah.hcl}; exit 1'); then
              echo "ok : $i";
            fi;
          done